### PR TITLE
Add Czech language

### PR DESCRIPTION
**Pull request by Fjuro**
Please tell me if I need to add/change some other file as well

### CODE REVIEW

**Review by stephane-r — CHANGES_REQUESTED** [review]
Hi @Fjuro !

Thanks for your PR with Czech language :) Two small changes are missing : 

- add `cz` on language array in `src/components/Dialog/Language/index.tsx`
- add new `case` for `cz` language and update function params types in `src/utils/getLanguageName.ts` 

Thank again 💪

**Comment by Fjuro** [comment]
Done, thank you too for making an amazing app!
And sorry for this, I didn't really know what files to change 😅 let me know if everything is okay

**Comment by stephane-r** [comment]
Everything looks good :smiley: 

The "Favorites" text of the screenshot is hard, I will do another PR to fix the problem :+1: It's ok for me !



Thank you again @Fjuro

**Comment by stephane-r** [comment]
Fixed :) #167

**Comment by Fjuro** [comment]
You're welcome!

**Pull request merged**
